### ISSUE TITLE
Invalid SPIR-V produced when compiling kernels from Darktable

### ISSUE THREAD

**Issue by kpet** [google/clspv#1095]
Compiling the attached source with the following command line produces an invalid SPIR-V module:

```
clspv source.cl  -w -cl-fast-relaxed-math  -DNVIDIA=1 -I"/usr/share/darktable/kernels" -cl-single-precision-constant  -cl-kernel-arg-info   -fp16=0  -rewrite-packed-structs  -std430-ubo-layout  -decorate-nonuniform    -arch=spir  --use-native-builtins=acos,acosh,acospi,asin,asinh,asinpi,atan,atan2,atan2pi,atanh,atanpi,ceil,copysign,fabs,fdim,floor,fma,fmax,fmin,frexp,half_rsqrt,half_sqrt,isequal,isfinite,isgreater,isgreaterequal,isinf,isless,islessequal,islessgreater,isnan,isnormal,isnotequal,isordered,isunordered,ldexp,mad,rint,round,rsqrt,signbit,sqrt,tanh,trunc,  -spv-version=1.6  -max-pushconstant-size=256  -max-ubo-size=65536  -global-offset  -long-vector  -module-constants-in-storage-buffer  -cl-arm-non-uniform-work-group-size     -o compiled.spv
```

The module fails validation with the following message:

```
error: 9146: OpFunctionCall Argument <id> '7214[%7214]'s type does not match Function <id> '13162[%_ptr_StorageBuffer__struct_13161]'s parameter type.
  %7459 = OpFunctionCall %float %13164 %7351 %7214 %7214 %7215
```

[source.txt](https://github.com/google/clspv/files/11412430/source.txt)

**Comment by alan-baker** [comment]
Can you upload the includes?

**Comment by rjodinchr** [comment]
There are often many of them needed. It is easier to just clone [darktable](https://github.com/darktable-org/darktable) and update the include path.

**Comment by rjodinchr** [comment]
This test is failing because since the switch to opaque pointers, we have nothing to guarantee/check that pointer pass in argument to a function match what is expected in the function.
An easy fix is to inline all functions with a pointer in their argument list.
Doing so, we still end up with another issue:
```
error: line 1319: Header block '1112[%1112]' is contained in the loop construct headed by '1103[%1103]', but its merge block '1208[%1208]' is not
  %1112 = OpLabel
```

**Comment by alan-baker** [comment]
I think the first bug boils down to an implicit gep confusing type inference.

In the tonecurve kernel there are several calls like:
```
get_rgb_matrix_luminance(pixel, profile_info, profile_info->matrix_in, lut)
```

`matrix_in` is the first element of `profile_info` so LLVM is eliminating the gep. After that we happen to pick an array of floats for the type. `get_rbg_matrix_luminance` infers the correct type, but that's why there's a mismatch.

**Comment by alan-baker** [comment]
I'll take it. InlineFuncWithPointerBitCastArgPass is supposed to handle this, but it is currently making a limiting assumption. Even once it's inlined I need to double check clspv won't accidentally pick the worse type to infer.

**Comment by alan-baker** [comment]
The second part of this bug is a result of misusing the loop analysis in FixupStructuredCFG. The `clip_rotate_bicubic` function needs both a conditional header split and a continue isolated. Doing the split ruins the loop info. Instead we can apply these transforms in the other order. Longer term we should probably fix the loop info in case we have to add more transforms.
