### ISSUE TITLE
UNREACHABLE: User of a constant expression was a constant

### ISSUE THREAD

**Issue by jrprice** [google/clspv#120]
The relatively simple kernel below produces this error message:

```
User of a constant expression was a constant!
UNREACHABLE executed at ../../lib/UndoGetElementPtrConstantExprPass.cpp:74!
```

```
#define WGSIZE 4
__attribute__((reqd_work_group_size(WGSIZE, 1, 1)))
kernel void foo(global float *output)
{
  local float scratch[WGSIZE];

  uint lid = get_local_id(0);
  scratch[lid] = 0.f;
  barrier(CLK_LOCAL_MEM_FENCE);

  float tmp = 0.f;
  for (uint k = 0; k < WGSIZE; k++)
    tmp += scratch[k];

  output[0] = tmp;
}
```

**Comment by sheredom** [comment]
Hey James, you've encovered one of the... less well tested parts of the compiler - well done!

What a think is happening is:

* scratch gets moved to a global variable as that is how Vulkan represents local memory.
* the loop gets unrolled
* that means scratch[k], k is a constant
* and we had a ton of issues whereby LLVM will turn scratch[1] -> a GEP constant expression, which isn't allowed in Vulkan

I'm not certain _what_ the fix is off the top of my head, but I'll see if I can look into it!

**Comment by alan-baker** [comment]
Working as 00e7a58a2834ee938830f82b42a0692fc2232511 at least.
