### ISSUE TITLE
Impossible to determine the size of the POD buffer from the descriptor map

### ISSUE THREAD

**Issue by kpet** [google/clspv#185]
When using `-cluster-pod-kernel-args`, it is not possible for an application to know how much memory to allocate for the POD buffer without prior knowledge of the kernels used. Unless I've missed something, the best an application can do without prior knowledge is to figure out the maximum offset within the buffer from the descriptor map and assume a maximum size for an argument.

**Comment by dneto0** [comment]
That's true.   The use model assumes you already know what the argument types are. 
Is there a different use case you're thinking about?

**Comment by kpet** [comment]
Depending on your definition of use case, yes. I've been working on an OpenCL runtime layer that uses clspv (that I will release in the coming weeks). The host code can't know what the arguments are without compiling the source in that case. I had a (small) patch to clspv that added an `arg_size` field to the descriptor map that has rotted (I can't yet contribute to clspv). Before I consider re-implementing this on the latest version, I wanted to raise the issue and check whether the patch would be accepted (or even better if one of the regular clspv authors would be interested in implementing this :)).

**Comment by ericberdahl** [comment]
@kpet makes a valid observation about the gap between the use case for which clspv was originally created and his use case. As @dneto0 correctly observes, clspv presumes that the host app knows the size of the arguments it is passing and therefore can compute the size of the pod buffer given the appropriate offsets of each member.

@kpet's use case, building an OpenCL implementation on top of a conforming Vulkan implementation and clspv-built SPIR-V modules (my read of his response above), is still technically possible, but may be inefficient in the current clspv implementation. Because clspv's descriptor map does not include the size of each argument, an OpenCL implementation that uses clspv would need to either guess the required size of the pod buffer or defer pod buffer allocation until the NDRange were enqueued (ensuring that all arguments had been set). Either choice is less efficient than knowing a-priori the pod buffer size.

From this analysis, I expect the current clspv implementation is sufficient for most **applications**. I further expect that the current clspv implementation is sufficient, but not maximally efficient, for most **runtime layers**. YMMV
