### ISSUE TITLE
Add C++ API to clspv

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#242]
I will be adding a C++ API to clspv and doing some refactoring to make this work (e.g. #236). My plan is to add functionality to satisfy an OpenCL-like API (for clvk) and an API for our testing requirements. For example, I will add a function to compile from a source string. It will populate a binary container (`vector<uint32_t>`) and descriptor map container.

The descriptor map will turn into a simple data structure that is populated by clspv. I will add an ostream operator to print it to a file for command line usage. The data structure will look something like:
```
struct DescriptorMapEntry {
  enum Kind {
    Sampler,
    Kernel,
    Constant
  } kind;

  uint32_t descriptor_set;
  uint32_t binding;

  struct SamplerData {
   uint32_t mask;
   // Removed expression. Can rebuild on output.
   //std::string expression;
  } sampler_data;

 struct KernelArgData {
   std::string kernel_name;
   std::string arg_name;
   uint32_t arg_ordinal;
   ArgKind arg_kind;

   // Pointer-to-local data.
   uint32_t local_spec_id;
   uint32_t local_elem_size;

   // POD data.
   uint32_t offset;
   uint32_t arg_size;
 } kernel_arg_data;

  struct ConstantData {
    ArgKind kind;
    // Changed definition
    //std::string hex_bytes;
    std::vector<uint8_t> hex_bytes;
  } constant_data;

   DescriptorMapEntry(SamplerData &&data, uint32_t descriptor_set, uint32_t binding);
   DescriptorMapEntry(KernelArgData &&data, uint32_t descriptor_set, uint32_t binding);
   DescriptorMapEntry(ConstantData &&data, uint32_t descriptor_set, uint32_t binding);
};
```

The logging and error reporting will also change a bit. I haven't finalized on what it will look like, but there will likely be a version of the API that returns a simple result struct that contains an exit code and any messages as a string.

FYI @kpet, @ericberdahl, @dneto0. I would appreciate your comments and feedback on this proposal. I am developing this in parallel with the necessary changes to clvk to ensure it works seamlessly.

**Comment by dneto0** [comment]
The sampler mask values are defined by the OpenCL bits for the various parts (addressing mode, etc.)  Need to document where we take those numbers from. (I think it's the CLK_* enums.)

The sampler string expression is purely informational since it repeats exactly the info in the mask.  I think we also canonicalize it.

Currently a KernelData struct is always 1-1 with a kernel argument.  So I'd probably rename the struct to KernelArgData

Nits:
  - missing the ArgKind definition
  - need to comment on conventions for the partial data cases for POD and ptr-to-local.

This proposal is missing the info for module-constants-in-storage-buffer.  They are lines starting with "constant,".  E.g. see test ProgramScopeConstants/in_storage_buffer_descriptor_map_arr_vec3.cl

**Comment by dneto0** [comment]
(and thanks for doing this!)  :-)

**Comment by dneto0** [comment]
Nit:  You forgot to add close brace for the KernelData. :-)

**Comment by alan-baker** [comment]
I've added constant data to the proposal. I renamed to KernelArgData as suggested. I also removed the . sampler expression since it can be calculated. It will still be included in the file dump.

**Comment by kpet** [comment]
Great to see an online API taking shape. Overall this looks like a good first step. I can think of several things we're going to want to add/change over time but I think it's easier to put a stake in the ground with an API for the current state and then iterate rather than trying to fully design it.

The only thing I really think should be changed for v1 is `ConstantData::hex_bytes`. Why pass this as a hex string instead of raw data stored in say a vector of bytes? This forces all consumers to implement a parser. I'd expect the typical consumer to just want to copy the data to a buffer.

>there will likely be a version of the API that returns a simple result struct that contains an exit code and any messages as a string.

Does this mean that you want to tackle implementing error handling in all passes at the same time? The current approach of crashing will no longer be acceptable for clvk if clspv is running in the application's process.

**Comment by dneto0** [comment]
I agree the constant data should be a counted array of bytes, not a hex string.

As for crashing...  Yes that's bad.  I believe the cases are for failing asserts.  Over time those would have to be eliminated or turned into real user errors.

**Comment by ericberdahl** [comment]
I'm missing the intention and/or purpose. The concept of "adding a C++ API to a <<compiler>>" doesn't speak to me, so perhaps I'm missing the goal. On it's face, how the compiler implements its support of its work seems like its internal business. On the flip side, if the purpose is to assist consumers, I believe that should be loosely coupled to the compiler and not a part of it.

There are additional observations about he design and/or reusability of the descriptormap data structure I'd offer, but I'm concerned about making comments that are more tangential than helpful.

**Comment by alan-baker** [comment]
I've modified the hex bytes initialization in my proposal and its working on my branch.

My immediate goal for error messaging to was provide control to application about how messages are handled. Currently all messages go to llvm::errs() or llvm::outs(). I agree that crashing is bad, but I can't fix all the assertion cases in this first change.

I do think our long term goal should be improving robustness and adding graceful errors.

**Comment by ericberdahl** [comment]
The way the struct in the original post is authored, should the content instead by a union? That is, exactly one of sampler_data, kernel_arg_data, and constant_data should be valid in any given instance of the struct. Which one is valid can be inferred from the kind. Therefore, those three elements should be members of a union, no?

**Comment by alan-baker** [comment]
Now that it is public I can say we plan to integrate this into [Amber](https://github.com/google/Amber) (see https://github.com/google/amber/issues/29) for testing purposes.
