### ISSUE TITLE
Expose an executable capable of running clspv-specific passes

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#263]
@dnovillo 

Executable like llvm-opt to run individual passes to provide better unit testing.

**Comment by dnovillo** [comment]
Thanks.  Can't seem to be able to assign it to myself.  Do I need to be added somewhere?

**Comment by alan-baker** [comment]
Need to get you added as a collaborator. @dneto0 can you add Diego?

**Comment by dnovillo** [comment]
@dneto0 ping?

**Comment by dnovillo** [comment]
So, some initial ideas for this:

1. Add a tools/clspv-opt binary which  will take LLVM IR and emit LLVM IR.
2. I'm assuming that the current clspv driver cannot output LLVM IR, so I will need to add that option.
3. A new PassManager class in lib/Passes.cpp so that passes can be scheduled via an API for clspv-opt or  other future tools.

@dneto0  @alan-baker  Other requirements?

@dneto0 I still don't seem to have access as a collaborator.  Help?
