### ISSUE TITLE
openclc.h

### ISSUE THREAD

**Issue by moozoo64** [google/clspv#293]
Where do I find openclc.h

I can compile clspv fine but when I run it I get
<built-in>:337:10: fatal error: 'openclc.h' file not found
Its mentioned in the source in lib/Compile.cpp
Googling "openclc.h" comes back with one hit related to the Radeon GPU Analyzer which is saying openclc.h is actually opencl_c.h?

**Comment by alan-baker** [comment]
It is the dummy name for the pre-baked opencl header clspv uses, opencl_builtins_header.h. Make sure the file has been generated in <build dir>/include/clspv.

I believe there was range of commits where some of the make dependencies were incorrect (fixed by 2e7b8098874ea1c339afe4c58562346bdeee3432).
