### ISSUE TITLE
Support for per-kernel push constants

### ISSUE THREAD

**Issue by kpet** [google/clspv#529]
Basic support for push constants was introduced recently. In the current implementation, all kernels in a module share the same push constants. While simple, this is sub-optimal and will get in the way of implementing https://github.com/google/clspv/issues/528. This issue covers changing the current implementations so that each kernel in a module can use a different set of push constants. Since each entrypoint can only statically use one push constant block (see 14.5.1 in the Vulkan spec), this means that each kernel will need to have its own structure type for push constants.

**Comment by alan-baker** [comment]
Here is my plan for this:
1. Add the ability to generate POD args in push constants by explicit option
  * incompatible with current push constants
  * must be clustered args
  *. will check against a specified size (default 128B)
2.  Make clustering pod args the default
3. Change current module scope push constants to be specialization constants
  * this will allow drivers to optimize the bounds checking away
  * current push constants will be translated as specialization constants with null initializers
  * new enum for identifying them (since they need to be per-component)
4. Change the selection of POD args storage type to be automatic
  * priority will be: push constant (size limited, no arrays for now), ubo (layout ok), ssbo
  * still allow overrides
  * allow each kernel to make a decision independently
  * probably refactor layout checks
5. Add more options to specify the environment and affect POD arg choices (e.g. 16-bit storage capabilities)

On the clvk side:
1. Support pod push constants, but don't use them by default (after clspv's 1st action)
2. Change current push constants to spec constants (after clspv's 3rd action)
3. Stop sending specific choices about POD args (after clspv's 4th action)

Each action is intended to be a separate PR. The key integration points with clvk will be after switching to spec constants and them after introducing auto assignment of pod args. @kpet I will plan to handle the clvk integration as this occurs.

**Comment by kpet** [comment]
This sounds generally excellent but I don't think I fully agree with 3.

Using specialisation constants for `get_work_dim()` is fine as the number of possibilities is small and the performance impact of having to recompile can probably be mitigated well by pipeline caching. As previously discussed, exploring the use of specialisation constants was the reason I left https://github.com/google/clspv/issues/341 open.

When it comes to global offsets though, I'm really not convinced these should be implemented with specialisation constants. Having to recompile each time the global offset changes feels wasteful.

Also, the non-uniform region support I've been working on currently uses push constants for the region offset (+global offset). We'd still need a few recompilations because of the multiple workgroup sizes but caching is more likely to help with WG sizes than region offsets. Further changes to Vulkan would make this issue go away entirely (not any time soon though).

All in all I would really like to retain the ability to use/benchmark push constants for things other than POD arguments without having to essentially re-implement support from scratch.

Can't the two be reconciled by making existing push constants look like additional POD arguments with a pre-defined name/type/field in the descriptor map?

>this will allow drivers to optimize the bounds checking away

Assuming you're talking about the bound checking on the input dimension for the work-item built-in functions, I'm really not concerned since in the typical usage pattern they are known statically.

**Comment by alan-baker** [comment]
>Can't the two be reconciled by making existing push constants look like additional POD arguments with a pre-defined name/type/field in the descriptor map?

The only way to do this that makes sense to me is for all kernels to share the push constant interface. This means needing to convert all the clustered arguments into a single type abstraction and adding type conversion code in every kernel. This seems less desirable to me.

The non-uniform regions seem least affected by this proposal because the workgroup sizes will also change.

**Comment by kpet** [comment]
Another idea: could we nest structures?

```
struct push_constants_for_kernel_A {
  struct pod_push_constant_arguments_for_kernel_A pods;
  struct other_push_constants other;
};
```

or

```
struct push_constants_for_kernel_A {
  struct pod_push_constant_arguments_for_kernel_A pods;
  // other push constants
};
```

>The non-uniform regions seem least affected by this proposal because the workgroup sizes will also change.

As I said above :). But modules built for specific workgroup sizes are more likely to hit in the cache over the lifetime of a program than modules built for specific region and/or global offsets.

**Comment by alan-baker** [comment]
The nesting problem is the same. It is only feasible if kernels are fully inlined. Otherwise, the compiler cannot disambiguate which variable to reference.

I also don't want separate structs for each kernel in a global variable because push constant sizes are so limited.

**Comment by kpet** [comment]
>The nesting problem is the same. It is only feasible if kernels are fully inlined. Otherwise, the compiler cannot disambiguate which variable to reference.

Right, I thought your worry was to have to rewrite/modify the clustered POD argument structure. I'd forgotten the elephant in the room.

I don't have a brillant idea to make this work for truly per kernel push constants (apart from specialising the entire call tree when a function is using a push constant).

The next best thing would be to have all per-kernel push constant structure types share the same first members that would be a union of all the members requested by all the kernels in the module. Storage-size-wise I don't think it's too bad (32 bytes worst case with the current push constants, a bit better with support for scalar block layout). The indices would always be the same, only the global variable accessed would change (assuming we can use a common type to access the first few members). The entire call tree of functions that use push constants would need to be rewritten to pass a pointer to the first few members of the global variable for each kernel but we wouldn't need to duplicate code.

>I also don't want separate structs for each kernel in a global variable because push constant sizes are so limited.

I'm definitely not suggesting we do that :). This would scale poorly to (even not that) big modules.

**Comment by alan-baker** [comment]
If we're discussing benchmarking then, I'd say let's add another step at the end that uses the single global variable and abstracted types to compare against unique interfaces and spec constants. There is value in being able to generate more kinds of spec constants anyways.

**Comment by kpet** [comment]
Not sure what you're proposing to compare against what exactly but benchmarking sounds good. If we can't measure a difference (even on a constructed worst case), then which way we go doesn't matter and simplicity should prevail.

>There is value in being able to generate more kinds of spec constants anyways.

+1 and value in being able to pick the best solution in cases where knowledge about the workload is available.

**Comment by alan-baker** [comment]
My proposal is comparing workloads using pod args as push constants + spec constants for current push constants vs trying to put everything into push constants in a single interface. The latter is more complicated in clspv and you run out of push constants more often (assuming you use offset, etc), but improves caching.

**Comment by kpet** [comment]
That's what I thought, thanks for confirming.

**Comment by alan-baker** [comment]
This is complete.
