### ISSUE TITLE
Unreachable hit: Support above GEP on PointerBitcastPass

### ISSUE THREAD

**Issue by PlasmaPower** [google/clspv#723]
This kernel https://gist.github.com/PlasmaPower/75b1e84f949d761e27bc283014ebb4ae hits the unreachable here https://github.com/google/clspv/blob/589d72ecbf5b1ea813d1b3d1b7a43cbd6d220c87/lib/ReplacePointerBitcastPass.cpp#L278

I've been unable to produce an MRE so far, but it's something with the LLVM getelementpointer.

**Comment by PlasmaPower** [comment]
I've finally reduced this issue with the help of a program that randomly removes lines of code and checks if it still crashes:
```c
typedef uint arr[10];

void example() {
	const arr one = {1};
}
```

**Comment by PlasmaPower** [comment]
This seems to be still failing, albeit with a different error message than the one indicated in the original issue:
```
  %4 = getelementptr inbounds <{ i32, [9 x i32] }>, <{ i32, [9 x i32] }>* %2, i32 0, i32 0  %4 = getelementptr inbounds <{ i32, [9 x i32] }>, <{ i32, [9 x i32] }>* %2, i32 0, i32 0[1]    1591586 segmentation fault (core dumped)  clspv kernel.cl
```
It might just be that my current build doesn't have debug assertions though

**Comment by rjodinchr** [comment]
Hi @PlasmaPower,

This example is still failing on the same line you mentioned above.
It still needs to be fixed in clspv.

But even after this issue is fixed, your example won't compile for 2 reasons:
- printf is not supported yet
- the code is doing cast that are not supported in clspv yet (storing an i8 to an element declared as i64).
