### ISSUE TITLE
crash on a specific input

### ISSUE THREAD

**Issue by FROL256** [google/clspv#795]
Hello. I have updated clspv today and got crash on my project. I tried to isolate bug, but it actually reproduces  only under certain circumstances depend on different places of a code. So, please see archive where i did my best to isolate it )

https://drive.google.com/file/d/13Rw_2NVY5nGfccz_74Q0S0XS9zX-nHEH/view?usp=sharing

Lines 3, 56, 57 and 72 -- al of them influence on crash.

**Comment by rjodinchr** [comment]
I had a look at it.
It is due to the pass transforming vec3 into vec4, where the PHI Nodes are not supported yet.
2 possibilities from there:
- implement PHI nodes support in this pass
- add an option to explicitly disable this pass, which might not be needed in your case.
I will try to create PR for both before the end of the week so that we can at least cherry-pick one of them.

**Comment by rjodinchr** [comment]
I think we can now close this issue

**Comment by FROL256** [comment]
yep, it works for me, thank you very much!
