### ISSUE TITLE
8/16 element vectors unsupported

### ISSUE THREAD

**Issue by kpet** [google/clspv#8]
A simple source file like:

```c
__kernel void testv16()
{
	float16 f;
}
```

Produces the following error message:

```
$ ./build/bin/clspv vec16.cl 
vec16.cl:3:9: error: expected ';' after expression
        float16 f;
               ^
               ;
vec16.cl:3:2: error: use of undeclared identifier 'float16'
        float16 f;
        ^
vec16.cl:3:10: error: use of undeclared identifier 'f'
        float16 f;
                ^

```

Unsurprising given that the SPIR-V `Vector16` capability currently depends on the `Kernel` capability.

_Before someone makes a comment on that, I did notice it was a documented restriction. Do people find issues useful to track lifting these restrictions?_

**Comment by dneto0** [comment]
Clspv targets Vulkan.  I don't know of any Vulkan implementations that allow vectors larger than 4 elements.  So this is a deliberate restriction.

> Before someone makes a comment on that, I did notice it was a documented restriction. Do people find issues useful to track lifting these restrictions?

:-)

I think it's useful to track if the output of Clspv could run on *some* Vulkan implementation, even allowing for vendor extensions.  Otherwise I think it's best to mark as Invalid.    I just made up this rule. What do you think?

Even with such a rule, I think we should consider changes that enable development of experimental features in a Vulkan implementation.  For example, someone may want to extend Mesa's Vulkan implementation and finds something like OpenCL C to be the best shader programming model.  I think it's reasonable to allow that, perhaps under a command line flag explicitly opting into the experimental behaviour.
