### ISSUE TITLE
Switch to opaque pointers

### ISSUE THREAD

**Issue by alan-baker** [google/clspv#816]
LLVM is moving towards using opaque pointers generally. The information that used to be in the pointer element type is available on GEPs and load/store instructions. Clspv needs to switch uses of `getNonOpaquePointerElementType()` to more robust ways of accessing the desired type.

Conversions needed:

- [x] AllocateDescriptors (bidirectional)
- [x] AutoPodArgs
- [x] ClusterPodKernelArguments
- [x] Builtins (only used in type mangling)
- [x] DefineOpenCLWorkItemBuiltins
- [x] DirectResourceAccess
- [x] LongVectorLowering (partial, just missing memcpy)
- [x] MultiVersionUBOFunctions
- [x] NormalizeGlobalVariables (bidirectional)
- [x] PushConstants
- [x] ReplaceLLVMIntrinsics (memset and memcpy)
- [x] ReplaceOpenCLBuiltin
- [x] ReplacePointerBitcast (bidirectional)
- [x] SPIRVProducer (partial)
- [x] SimplifyPointerBitcast
- [x] SpecializeImageTypes (bidirectional)
- [x] ThreeElementVectorLowering
- [x] UBOTypeTransform (partial)
- [x] UndoByval
- [x] UndoInstCombine
- [x] ZeroInitializeAllocas
- [x] UndoSRet
- [x] Types
- [x] Builtin library from libclc
- [x] InlineFuncWithPointerBitCastArg (bidirectional)
- [x] llvm.memset and llvm.memcpy (@rjodinchr)

The overall strategy for the transition is:
1. Support both modes concurrently.
2. Get CTS and important benchmarks passing with opaque pointers.
3. Switch the default to opaque.
4. Remove support for transparent pointers after some period of stability.

**Comment by alan-baker** [comment]
For the SPIRVProducer, something along the lines of splitting getSPIRVType into two methods: getSPIRVType and getSPIRVPointerType should work. The new method would look something like:
```c++
SPIRVID SPIRVProducerPass::getSPIRVPointerType(Type *PtrTy, Type* EleTy) {
  if (!isa<PointerType>(PtrTy)) {
    llvm_unreachable("Use getSPIRVType instead");
  }

  const unsigned addr_space = PtrTy->getPointerAddressSpace();
  const bool needs_layout = PointerRequiresLayout(addr_space);
  const uint32_t layout_idx = needs_layout ? 1 : 0;

  if (addr_space != AddressSpace::UniformConstant) {
    if (EleTy->isStructTy() && dyn_cast<StructType>(EleTy)->isOpaque()) {
      return getSPIRVType(EleTy, needs_layout);
    }
  }

  auto ele_id = getSPIRVType(EleTy, needs_layout);
  auto &addrspace_entry = PointerTypeMap[addr_space];
  // Map of type maps
  auto &type_entry = addrspace_entry[EleTy];
  SPIRVID RID;
  if (type_entry.empty()) {
    type_entry.resize(2);
  }
  if (!type_entry[layout_idx].isValid()) {
    SPIRVOperandVec Ops;

    // Generate OpTypePointer.
    //
    // OpTypePointer
    // Ops[0] = Storage Class
    // Ops[1] = Element Type ID
    Ops << GetStorageClass(addr_space) << ele_id;
    RID = addSPIRVInst<kTypes>(spv::OpTypePointer, Ops);
  } else {
    RID = type_entry[layout_idx];
  }
  return RID;
}
```

**Comment by aeubanks** [comment]
some context: https://llvm.org/docs/OpaquePointers.html

**Comment by alan-baker** [comment]
@callumfare I have updated this issue with the task list for this conversion in terms of known issues. Obviously considerable testing will be required. If you wish to contribute to any unfinished and unassigned item I would greatly appreciate the help.

**Comment by omarahmed1111** [comment]
I had an idea to standardize a little some of the transitioning work for the passes:

1. Modify InferType so that when it recurse down through function definitions to infer the type and when it is successful and heading back through recursive calls, it stores the types of the arguments of the called function too inside type cache. (I think this already is there but not sure)
2. Modify InferType so that it will not return when it finds the type directly, but when it finds the type, it will continue seeing if there is a use with a call instruction and infer the argument of the called function with the type it already got and store it in type_cache.
3. Do the same for non pointer types inside InferType. So that if it is not a pointer type. It will not return the type directly but search for call instruction uses and update the called functions with the type.
4. Ensure that we move on functions on level order by moving on them like a bfs graph traversal. That will ensure that when we infer the types we always find them.
5. Ensure we always use InferType inside the pass and not getType. as InferType will ensure a proper handling for types for us.

**Comment by AnthonyTStephens** [comment]
use chrome #ffff for storage identifiers and short forms

**Comment by rjodinchr** [comment]
The transition is almost complete.
Here is what is left:
 - clean `Option.cpp`
 - clean `SPIRVProducer.cpp`
