### ISSUE TITLE
Is it possible to release clspv?

### ISSUE THREAD

**Issue by daemyung** [google/clspv#883]
Now I'm working for publishing clspv on conan which is the package manager. They require to download source from the release like [this](https://github.com/google/shaderc/tags). Could you make a release?

**Comment by alan-baker** [comment]
Clspv is a prototype. I'm not certain it is ready for a release per se.

Logistically speaking, this is also tricky as clspv is probably not the thing that needs versioned alone. Clspv's releases would likely be tied to LLVM's releases since the two are tightly coupled. I also consider the main consumer of clspv to be [clvk](https://github.com/kpet/clvk). It would make sense to coordinate on overall versioning scheme with it. I know @kpet has had some thoughts in this area.

**Comment by daemyung** [comment]
I see. Currently I'm implementing [CLMTL](https://github.com/daemyung/clmtl) and Clspv is used for the online compiler. Other dependencies are managed by the package manager so I hope Clspv is also managed by this. But Now I understand your stands. I will do this with WA. Thanks and I will close this issue.

**Comment by oscarbg** [comment]
@daemyung seeing clmtl repo.. great project! two requests:
can you activate issues tab? then I could ask there..
also can activate build artifacts on github actions?
finally can share performance vs Apple CL framework running for example clpeak.. thanks!

**Comment by daemyung** [comment]
@oscarbg Thanks for your interest.

- Ok I will open the issues tab. It's no problem. I just closed it because currently many features aren't implmented.
- Do you know how to do that?
- Currently it's not optimized. So the performance will be very bad...
